### ISSUE TITLE
Visitor - SingleProduct

### ISSUE THREAD

**Issue by andressantos94** [GS-AlphaForceMega/graceshopper#7]
As visitor, I want to view the details for an individual product (including product descriptions, photos and reviews), so that I can determine whether that particular item fits my needs

**Comment by NickMaslov** [comment]
We don't need to create SingleItemPage. Enough ListItem with button +Add to cart+

**Comment by NickMaslov** [comment]
ItemList component  <b>vs.</b> SingleItemPage(included review from users)
